set(SIGILVM_ROOT_DIR ${CMAKE_SOURCE_DIR})

set(SIGILVM_SOURCE_DIR
    ${SIGILVM_ROOT_DIR}/src
)

set(SIGILVM_INCLUDE_DIR
    ${SIGILVM_ROOT_DIR}/include
)

set(SIGILVM_ASSET_DIR
    ${SIGILVM_ROOT_DIR}/assets
)

set(SIGILVM_TEST_DIR
    ${SIGILVM_ROOT_DIR}/tests
)