message(STATUS "")
message(STATUS "========================================")
message(STATUS "SigilVM Ready")
message(STATUS "Version: ${SIGILVM_VERSION}")
message(STATUS "Build Type: ${CMAKE_BUILD_TYPE}")
message(STATUS "Build Dir: ${CMAKE_BINARY_DIR}")
message(STATUS "Compiler: ${CMAKE_CXX_COMPILER_ID}")
message(STATUS "System: ${CMAKE_SYSTEM_NAME}")
message(STATUS "========================================")
message(STATUS "")